name: CRM Build

on: push

jobs:
  build:
    runs-on: windows-latest #[self-hosted, crm]
    steps:
      
      - uses: actions/checkout@v3

      # - name: Install Power Platform CLI
      #   run: |              
      #     Invoke-WebRequest "https://aka.ms/powerplatform-cli-download" -OutFile "$env:TEMP\pac.zip"; Expand-Archive "$env:TEMP\pac.zip" -DestinationPath "$env:TEMP\pac-cli" -Force
      #     & "$env:TEMP\pac-cli\pac.exe" solution pack --folder "src/unpacked-solution" --zipFile "build/dynamic365.zip"
      
      # - name: Install Power Platform CLI
      #   run: |
      #     dotnet tool install --global Microsoft.PowerPlatform.Cli
      #     echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      
      # - name: Install Power Platform Tools
      #   uses: microsoft/powerplatform-actions/actions-install@v1      
      
      - name: Download and run Power Platform CLI
        shell: pwsh
        run: |
           # Load required .NET assembly
            Add-Type -AssemblyName System.IO.Compression.FileSystem

            # Define paths
            $zipUrl = "https://aka.ms/powerplatform-cli-download"
            $downloadPath = "$env:TEMP\pac.zip"
            $extractPath = "$env:TEMP\pac-cli"

            # Clean up any previous downloads
            Remove-Item -Path $downloadPath -ErrorAction SilentlyContinue
            Remove-Item -Path $extractPath -Recurse -Force -ErrorAction SilentlyContinue

            # Download ZIP with basic parsing
            Invoke-WebRequest -Uri $zipUrl -OutFile $downloadPath -UseBasicParsing

            # Validate ZIP file size
            if ((Get-Item $downloadPath).Length -lt 10000) {
                throw "Downloaded file is too small — likely not a valid ZIP. Check the URL or network."
            }

            # Extract ZIP
            [System.IO.Compression.ZipFile]::ExtractToDirectory($downloadPath, $extractPath)

            # Run pac
            & "$extractPath\pac.exe" solution pack --folder "src/unpacked-solution" --zipFile "build/dynamic365.zip"
              
      - name: Packing CRM Solution
        run: |
          pac solution pack --folder "customer-service" --zipFile "customer-service.zip"
        shell: C:\Program Files\PowerShell\7\pwsh.EXE
      
      - uses: actions/upload-artifact@v4
        with:
          name: crm-solution
          path: build/dynamic365.zip