name: CRM Build

on: push

jobs:
  build:
    runs-on: windows-latest #[self-hosted, crm]
    steps:
      
      - uses: actions/checkout@v3

      - name: Install Power Platform CLI
        run: |    
          # Load required assembly manually (needed in PowerShell 7)
          Add-Type -AssemblyName System.IO.Compression.FileSystem

          # Define paths
          $pacZipUrl = "https://aka.ms/powerplatform-cli-download"
          $downloadPath = "$env:TEMP\pac.zip"
          $extractPath = "$env:TEMP\pac-cli"

          # Download the ZIP
          Invoke-WebRequest -Uri $pacZipUrl -OutFile $downloadPath

          # Extract using .NET API (works in PS7)
          [System.IO.Compression.ZipFile]::ExtractToDirectory($downloadPath, $extractPath)

          # Run pac from extracted binaries
          & "$extractPath\pac.exe" solution pack --folder "src/unpacked-solution" --zipFile "build/dynamic365.zip"
          #Invoke-WebRequest "https://aka.ms/powerplatform-cli-download" -OutFile "$env:TEMP\pac.zip"; Expand-Archive "$env:TEMP\pac.zip" -DestinationPath "$env:TEMP\pac-cli" -Force
          #& "$env:TEMP\pac-cli\pac.exe" solution pack --folder "src/unpacked-solution" --zipFile "build/dynamic365.zip"
      
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
      
      # - name: Install Power Platform CLI
      #   run: |
      #     dotnet tool install --global Microsoft.PowerPlatform.Cli
      #     echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
            
      - name: Packing CRM Solution
        run: |
          & "$env:TEMP\pac-cli\pac.exe" solution pack --folder "src/unpacked-solution" --zipFile "build/dynamic365.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: crm-solution
          path: build/dynamic365.zip