name: CRM Build

on: push

jobs:
  build:
    runs-on: windows-latest #[self-hosted, crm]
    steps:
      
      - uses: actions/checkout@v3

      # - name: Install Power Platform CLI
      #   run: |              
      #     Invoke-WebRequest "https://aka.ms/powerplatform-cli-download" -OutFile "$env:TEMP\pac.zip"; Expand-Archive "$env:TEMP\pac.zip" -DestinationPath "$env:TEMP\pac-cli" -Force
      #     & "$env:TEMP\pac-cli\pac.exe" solution pack --folder "src/unpacked-solution" --zipFile "build/dynamic365.zip"
      
      # - name: Install Power Platform CLI
      #   run: |
      #     dotnet tool install --global Microsoft.PowerPlatform.Cli
      #     echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      
      # - name: Install Power Platform Tools
      #   uses: microsoft/powerplatform-actions/actions-install@v1      
      
      - name: Download and run Power Platform CLI
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/powerplatform-cli-wrapper.git
          cd powerplatform-cli-wrapper
          npm install
          npm install -g gulp-cli
          gulp ci

      - name: Packing CRM Solution
        run: |
          pac solution pack --folder "customer-service" --zipFile "customer-service.zip"
        
      
      - uses: actions/upload-artifact@v4
        with:
          name: crm-solution
          path: build/dynamic365.zip