name: CRM Build

on: push

jobs:
  build:
    runs-on: windows-latest #[self-hosted, crm]
    steps:
      - uses: actions/checkout@v3

      - run: pac solution pack --folder "src/unpacked-solution" --zipFile "build/dynamic365.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: crm-solution
          path: build/dynamic365.zip