name: CRM Build

on: push

jobs:
  build:
    runs-on: windows-latest #[self-hosted, crm]
    steps:
      
      - uses: actions/checkout@v3

      - name: Install Power Platform CLI
        run: |          
          # Download and install the Power Platform CLI MSI installer
          Invoke-WebRequest -Uri "https://aka.ms/PowerAppsCLI" -OutFile "pacli.msi"
          Start-Process -FilePath "msiexec.exe" -ArgumentList "/i pacli.msi /qn" -Wait
          # Add the PACLI to the PATH (if not already added by the installer)
          $env:Path += ";C:\Program Files\Microsoft PowerApps CLI"
          Write-Host "Power Platform CLI installed and added to PATH."
      
      # - name: Install Power Platform Tools
      #   uses: microsoft/powerplatform-actions/install-tools@v1
      
      - name: Packing CRM Solution
        run: |
          pac solution pack --folder "src/unpacked-solution" --zipFile "build/dynamic365.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: crm-solution
          path: build/dynamic365.zip