name: CRM Build

on: push

jobs:
  build:
    runs-on: windows-latest #[self-hosted, crm]
    steps:
      
      - uses: actions/checkout@v3

      # - name: Install Power Platform CLI
      #   run: |
      #     $installer = "$env:TEMP\pac.msi"
      #     Invoke-WebRequest -Uri "https://aka.ms/powerplatform-cli-download" -OutFile $installer
      #     Start-Process msiexec.exe -Wait -ArgumentList "/i $installer /quiet"
          
      #     # Add CLI path to environment
      #     $cliPath = "C:\Program Files\Microsoft Power Platform Tools"
      #     $env:PATH += ";$cliPath"
      #     [Environment]::SetEnvironmentVariable("PATH", $env:PATH, [EnvironmentVariableTarget]::Process)

      #     # Verify installation
      #     pac --version

      
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/install-tools@v1
      
      - name: Packing CRM Solution
        run: |
          pac solution pack --folder "src/unpacked-solution" --zipFile "build/dynamic365.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: crm-solution
          path: build/dynamic365.zip