name: Solution Check
on:
  workflow_dispatch:
    inputs:
      sample_name:
        description: Which sample do you want to run a solution check on?
jobs:
  check-solution:
    runs-on: windows-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Install Power Platform CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool

      - id: pac-solution-pack
        name: pac-solution-pack
        shell: pwsh
        run: |
           pac solution pack --folder "samples\a-puzzle-a-day" --zipFile "build/a-puzzle-a-day.zip" #--zipfile samples/${{ github.event.inputs.sample_name }}/solution/${{ github.event.inputs.sample_name }}.zip --folder samples/${{ github.event.inputs.sample_name }}/sourcecode --packagetype Unmanaged --processCanvasApps

      - id: pac-solution-check
        name: pac-solution-check
        shell: pwsh
        run: |
          pac solution check --path samples/${{ github.event.inputs.sample_name }}/solution/${{ github.event.inputs.sample_name }}.zip --outputDirectory samples/${{ github.event.inputs.sample_name }}/solution/ --geo UnitedStates

      - uses: actions/upload-artifact@v4
        with:
          name: crm-solution
          path: build/a-puzzle-a-day.zip